# permissions for end users to view buckets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: acme-bucket
    app.kubernetes.io/managed-by: kustomize
  name: bucket-viewer-role
rules:
- apiGroups:
  - cloud.acme.local
  resources:
  - buckets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cloud.acme.local
  resources:
  - buckets/status
  verbs:
  - get
