apiVersion: cloud.acme.local/v1
kind: Bucket
metadata:
  labels:
    app.kubernetes.io/name: acme-bucket
    app.kubernetes.io/managed-by: kustomize
  name: bucket-sample
spec:
  # TODO(user): Add fields here
